version: '3.8'

services:
    ticketproxy:
        image: nginx:1.21-alpine
        depends_on:
            - "ticketapi"
            - "ticketclient"
        volumes:
            - ./TicketProxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '7000:80'

    ticketclient:
        container_name: ticket-client
        build:
            context: ./TicketClient
        restart: on-failure
        depends_on:
            - "ticketapi"
            
    ticketapi:
        container_name: ticket-api
        build:
            context: ./TicketApi
        restart: on-failure
        depends_on:
            - "rabbitmq"
        
    ticketsender:
        container_name: ticket-sender
        build:
          context: ./TicketSender
        restart: always
        depends_on:
            - "rabbitmq"
        
    rabbitmq: # login guest:guest
        image: rabbitmq:3-management
        hostname: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"