version: '3.8'

services:
    ticketproxy:
        image: nginx:1.21-alpine
        depends_on:
            - "ticketapi"
            - "ticketclient"
        volumes:
            - ./TicketProxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '7000:80'

    ticketclient:
        build:
            context: ./TicketClient
        restart: on-failure
        depends_on:
            - "ticketapi"
            
    ticketapi:
        build:
            context: ./TicketApi
        restart: on-failure
        depends_on:
            - "rabbitmq"
        
#    ticketsender:
#        build:
#          context: ./TicketSender
#        restart: always
#        depends_on:
#            - "rabbitmq"
        
    rabbitmq: # login guest:guest
        image: rabbitmq:3-management
        hostname: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"