version: '3.8'

networks:
    example:
        driver: bridge

services:
    ticketproxy:
        image: nginx:1.21-alpine
        depends_on:
            - "ticketclient"
        volumes:
            - ./TicketProxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '7000:80'
        networks:
            - example

    ticketclient:
        build:
            context: ./TicketClient
        restart: always
        networks:
            - example
#        depends_on:
#            - "ticketapi"
            
#    ticketapi:
#        build:
#              context: ./TicketApi
#        restart: always
#        depends_on:
#            - "rabbitmq"
        
#    ticketsender:
#        build:
#          context: ./TicketSender
#        restart: always
#        depends_on:
#            - "rabbitmq"
        
    rabbitmq: # login guest:guest
        image: rabbitmq:3-management
        hostname: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"