version: '3.8'

services:
    ticketproxy:
        image: nginx:1.21-alpine
        depends_on:
            - "ticketapi"
            - "ticketclient"
        volumes:
            - ./TicketProxy/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '7000:80'

    ticketclient:
        container_name: ticket-client
        build:
            context: ./TicketClient
        restart: always
        depends_on:
            - "ticketapi"
           
    ticketdb:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "49R8MXw#49c6wT9Q8!"
            MSSQL_PID: "Express"
        restart: always
        ports:
            - "1433:1433"
        depends_on:
            - "ticketapi"
           
    ticketapi:
        container_name: ticket-api
        build:
            context: ./TicketApi
        restart: always
        depends_on:
            - "rabbitmq"
        environment:
            db_container: "ticketdb"
            db_port: "1433"
            db_name: "Ticket"
            db_username: "sa"
            db_password: "49R8MXw#49c6wT9Q8!"
        
    ticketsender:
        container_name: ticket-sender
        build:
          context: ./TicketSender
          target: production
        restart: always
        depends_on:
            - "rabbitmq"
            - "ticketdb"
        
    rabbitmq: # login guest:guest
        image: rabbitmq:3-management
        hostname: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"