version: '3.8'

services:
    ticketclient:
        build:
              context: ./TicketClient
        restart: always
#        depends_on:
#            - "ticketapi"
            
#    ticketapi:
#        build:
#              context: ./TicketApi
#        restart: always
#        depends_on:
#            - "rabbitmq"
        
#    ticketsender:
#        build:
#          context: ./TicketSender
#        restart: always
#        depends_on:
#            - "rabbitmq"
        
    rabbitmq: # login guest:guest
        image: rabbitmq:3-management
        hostname: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"